### PR TITLE
Add fluted helmets

### PR DESCRIPTION
**Pull request by AppleTruce**
add helmet Fluted Falcon Grotesque Close Helm
add helmet Fluted Moustache Grotesque Close Helm
add helmet Fluted Angry Grotesque Close Helm
add helmet Fluted Bellows Close Helm

Added four top armor helmets

### CODE REVIEW

**Review by Meowkov — APPROVED** [review]
Assets working, XMLs looking good.

**Review by Erdertus — CHANGES_REQUESTED** [review]
@AppleTruce  Also touches Brigandines? Could be tidied to only touch the pauldrons, I think having it duplicated might make merging a pain in the ass for dev (not super sure though)

**Review by Erdertus — APPROVED** [review]
Approved with caveat duplicated in other PRs, merge numerically

**Comment by AppleTruce** [comment]
Addressed by PR #518 thank you Erdertus for your help

**Pull request closed without merging**
