### PR TITLE
Yeldur Dagger Rework

### PR DESCRIPTION
**Pull request by Yeldur**
Rework daggers to increase high tier cut options

Reworks Tanto, Seax and Ancient Long Dagger to increase higher tier dagger options in the form of Cut as they were originally built to be weaker than Stab-Only as they were intended to be able to block. As they can no longer block, a rework to increase stats makes sense.

Lowers the tier of Decorative Dagger as the stats given to it as a bonus for looms were too high for what the weapon is intended to be.

Tanto, Seax, ALD and DD are refunded as part of this rework.

### CODE REVIEW

**Review by Meowkov — APPROVED** [review]
Don't see any errors, good to go.

**Comment by Yeldur** [comment]
Not yet ready for merge yet so this can be left as draft for now :D

**Review by Erdertus — DISMISSED** [review]
Imo significantly changed tier on items should = refund, regardless of if it's a buff. so Ancient Long Dagger, Seax and Tanto.

More consistency in the naming of parts would be nice. For the "Decorative Long Dagger", the blade part ID is "crpg_black_longdagger_blade" and the name is "Long Dagger Blade" (name is exact same as "Ancient Long Dagger" blade).  I think all the pieces of the "Decorative Long Dagger" should be named as such, to try and avoid spaghetti in future? Tanto is a good example of consistency.

Neither of these are critical so you can just dismiss changes and I'll approve.

**Comment by Yeldur** [comment]
As far as part names, I roll with whatever they're submitted as by Meow, but I believe the names being similar is not too worrisome mostly from a perspective of that they are actually the same weapon, one just has a black handle which I think is distinguishing enough. 

I'm just speculating here but I believe if they had different part names we would have to duplicate the files(???) @Meowkov can probably speak more to that as he's the expert on that side of things.

**Review by Meowkov — APPROVED** [review]
Technically names and ids don't matter as long as they are setup correctly in the xmls.
IDs have to be unique though.
For weapons we can just have identical IDs to allow for mode switching while on pieces I think it will always just use the first one if two have identical IDs.

I will check that I adjust names of the pieces so they use the same naming ans the weapon itself in the future.
Would not touch existing ones but if you guys are touching something anyway, feel free to change names and IDs as long as they are consistent through all files.

Changes are looking good.

**Review by Erdertus — APPROVED** [review]
Approved

**Review by Muparadzi — APPROVED** [review]

**Pull request merged**
