### PR TITLE
Add Fluted Helmets 

### PR DESCRIPTION
**Pull request by AppleTruce**
Add 4 FLuted CLose Helms negates PR#499

### CODE REVIEW

**Comment by AppleTruce** [comment]
Adding 4 fluted helmets, negating #499  which unnecessarily touched brigandines in bodyarmor.xml and items.json.

**Review by Yeldur — APPROVED** [review]
Approved, looks good

**Review by Meowkov — APPROVED** [review]

**Comment by AppleTruce** [comment]
Is there something I need to do for that items.json conflict above?

**Review by Erdertus — APPROVED** [review]

**Comment by Muparadzi** [comment]
> Is there something I need to do for that items.json conflict above?

merge `main` into `02AddFlutedHelmets` and then run the exporter again

**Pull request merged**
