### PR TITLE
Salt additional2d

### PR DESCRIPTION
**Pull request by Erdertus**
Some 2D-swing polearms receive brace.

The following polearms have been made 2D-swing:
- Bamboo spear
- Awlpike
- Ancient Long Voulge
- Polesword
- Fine Steel Menavlion

The following polearms have had their lengths slightly reduced and some stats have changed in this process, tier has reduced:
- German Halberd (-5 reach, -1 thrust speed)
- Rhomphaia (-9 reach, -1 thrust speed, +1 swing speed)
- Burgundian Glaive (-13 reach, +1 swing speed)

Affected weapons refunded.

### CODE REVIEW

**Review by Meowkov — APPROVED** [review]
Looking good.

**Review by Muparadzi — APPROVED** [review]

**Review by Yeldur — COMMENTED** [review]
==rhompaia notes==
may potentially swing too fast given high weight of pole relative to low weight of head - it will be worth monitoring this just in case.

==burg glaive notes===
low weight on head relative to high weight on handle - this will likely cause it to swing much faster than it should
however, this is known entity as this is the classic "OP gigafast pole" - Approving for now but I think Burg Glaive may need to be adjusted to balance better in another PR - given length reduc though we can put pin in this for now as we watch new META form etc etc.

==bamboo spear notes==
stats for bamboo spear appear to be out-of-place tier wise

+0 3.3 tier
+3 5.2 tier

can this be avoided through increase of speed as opposed to dmg?
if dmg preferred can make exception to the ""rule"" but i think general pref of keeping items within at least a general realm of their base tier is a good goal to strive for. (but at the end of day it's +1 stab dmg on a low tier weapon, im not going to cry about it)

**Comment by Erdertus** [comment]
Rhompaia & Burg - Agreed to monitor, but worth noting I don't think I've changed the ratios. Pretty similar to before, so if they're broken now they were broken anyway lol. I'll put them on my play testing list post-patch

Bamboo Spear - Given it's already pretty low tier, when I was doing the stats, I wanted to keep them somewhat paired with before it could swing. Agreed it's out of sync for our usual path, but given it's an iconic cRPG1 weapon maybe we can make an exception, like peasant weapons?

**Review by Yeldur — APPROVED** [review]
fmb, approved

**Pull request merged**
