### PR TITLE
xbow STR increase items.json update

### PR DESCRIPTION
**Pull request by Yeldur**
Update items.json with new STR reqs for xbow.

### CODE REVIEW

**Review by Meowkov — APPROVED** [review]
Can not judge if this gets overwritten by stats autocalc but the changes are looking good.
EDIT: was changed in exporter, same results on other branches, all good! :)
Approved

**Review by Muparadzi — APPROVED** [review]

**Review by Erdertus — CHANGES_REQUESTED** [review]
Fine Light Crossbow and Simple Light Crossbow do not have an updated +0 & +1.

Heavy Maple Crossbow and Heavy Hunting Arabalest are missing, but they might be at the same STR req as before?

Refunds? Ammo too?

**Comment by Yeldur** [comment]
Refunds were done by yourself already in another PR and it was merged 

As far as Heavy Maple and Heavy Hunting, those both fall below the marker for increased STR req I believe so they stay they same.

Fight Light and Simple Light howeverrrrrrrrrrrr, I'll look into that, as far as I remember this was automatically calced by the exporter, so this may be normal(?)

**Comment by Yeldur** [comment]
Yeah there's definitely something funky with both of those, they should not be increasing in requirement. I'll have to take another look into this as idk why that is happening.

**Comment by Erdertus** [comment]
Does https://github.com/namidaka/itembalancing/pull/478 resolve the issue? I see it fixes Fine Light, is Simple Light okay in the end?

**Comment by Yeldur** [comment]
> Does #478 resolve the issue? I see it fixes Fine Light, is Simple Light okay in the end?

Simple Light is fine as is, there is no difference between 0 and 3 STR because you cannot be 0 STR and 3 STR is the absolute minimum stat requirement that everyone automatically has by default - The only issue really is lack of consistency but nobody uses the weapon and it's unlikely anyone will even notice it as a problem. 

I think long-term I will want to change something to potentially enable us to set static values for STR reqs or something alone those lines but that's something I can touch later on, for now this will be fine to mitigate issues.

**Review by namidaka — APPROVED** [review]

**Pull request merged**
