### PR TITLE
Added Lorica Musculata

### PR DESCRIPTION
**Pull request by Meowkov**
Added Lorica Musculata by GulagEnabler sponsored by Yeldur

### CODE REVIEW

**Comment by Erdertus** [comment]
Meow, review my changes please and confirm

**Review by Muparadzi — APPROVED** [review]

**Review by Yeldur — APPROVED** [review]
Approved

**Review by Meowkov — COMMENTED** [review]
Approved

**Review by Erdertus — APPROVED** [review]
Approved

**Pull request merged**
