### PR TITLE
Autocalc and export of current main without changes

### PR DESCRIPTION
**Pull request by Meowkov**
Currently main has some changes that were never auto calculated via the exporter.
This branch is current main after auto calc and export.
We want to merge this so the current main is actually reflecting all changes merged before.

For the smokebomb price I will open a new one to only change that back.

### CODE REVIEW

**Review by Erdertus — APPROVED** [review]
Approving in that it doesn't break anything, not sure what's "correct" (or even what's going on with these PR's ATM ^^ )

**Review by Yeldur — APPROVED** [review]
approved

**Comment by Muparadzi** [comment]
Was #473 not intended to add the xbow changes? The arrow stack count changes should be added here however.

**Comment by Meowkov** [comment]
@Muparadzi fixed the requirements being included and also the smokebomb value.
Ready for review again :D

**Review by Muparadzi — APPROVED** [review]

**Pull request merged**
