### PR TITLE
Added 1 polearm, 1 two hander and 10 one hander

### PR DESCRIPTION
**Pull request by Erdertus**
Reuploading as I think I did the rebase wrong or the rebase ended up including the holster changes that broke items because it was merged (sorry).
___________________________________________________________________________________________________________
Added weapons

Polearm: Great Long Axe
Two Hander: Large Falchion
One Hander: Arabian Cavalry Sword, Arabian Straight Sword, Kilij, Shamshir, Karabela, Noble Steel Scimitar, Solingen Sword, Heavy Arming Sword, Long Arming Sword & Decorated Thegn Blade

image
image
image

### CODE REVIEW

**Comment by Erdertus** [comment]
Re-review as adjusted Great Long Axe stats and reran exporter following Droobs polearm budget adjustment. Everything else untouched,

**Comment by namidaka** [comment]
@Meowkov  can you double check

**Comment by Erdertus** [comment]
As this includes a polearm it should wait until the valuemodel changes are put through before it is reviewed.

**Comment by namidaka** [comment]
@Erdertus  needs rebasing and conflics handled

**Comment by Erdertus** [comment]
@namidaka Conflicts merged and rebased

**Review by Yeldur — APPROVED** [review]
Approved, validated it met criteria outlined in checklist

**Comment by namidaka** [comment]
> Approved, validated it met criteria outlined in checklist

Approving this 2 times won't change anything . I'm still waiting for Meowkov to confirm that it's all good.

**Comment by Erdertus** [comment]
I requested re-review from Yeldur as I edited it since his last review, as this contains a polearm which was affected by the budget and length changes they received.

**Review by Meowkov — APPROVED** [review]
Removed some random whitespaces with a commit, PR exports fine, Thumbs generate without empty or missing images, items.json is not missing any items from the /items/ xmls files.
Approved.

**Pull request merged**
