### PR TITLE
Jamescross

### PR DESCRIPTION
**Pull request by Meowkov**
Added James Cross staff item

### CODE REVIEW

**Comment by Yeldur** [comment]
Stats set for h3 did result in 10.22 tier - justification is that i was unable to reach a lower tier whilst increasing damage, meaning that h3 would be forced into higher speed rather than a gain in damage (not what i was looking to do) - given that it is an increase in +1 damage and given that it is a staff weapon, abuse potential is low if it were overpowered as a result. can adjust if we believe this is problematic however.

**Comment by AppleTruce** [comment]
> Stats set for h3 did result in 10.22 tier - justification is that i was unable to reach a lower tier whilst increasing damage, meaning that h3 would be forced into higher speed rather than a gain in damage (not what i was looking to do) - given that it is an increase in +1 damage and given that it is a staff weapon, abuse potential is low if it were overpowered as a result. can adjust if we believe this is problematic however.

It's unlikely it would actually be a problem, but you may want to consider the perception people may have. Like oh wow staff just giving themselves special OP weapons and items now. It seems like a real potential PR mistake that some people could get a hold of and never drop again.

**Review by Erdertus — CHANGES_REQUESTED** [review]
Your +2 and +3 for the 2H version are the same.

For crafting alt mode weapons I find it useful to pick my "main" mode, do all the stats, set the weight (speed and handling) to where I would like for the alt mode, and then slowly drop damage until I fall back below the tier of the "main" mode and then tweak weights of the alt mode until just before going back over the tier of the "main" mode. The items.json will take the highest tier of either of the weapon modes.

Also agree with Apple, especially seeing as 1h maces are on the chopping block for being problematic, adding a T10.22 weapon locked to staff isn't a great look. Should be <T10 to be safe.

**Comment by Yeldur** [comment]
kk, will have to leave this one out for now as it will take me a while to fully rebalance the weapon again

**Comment by Yeldur** [comment]
Kk no worries, I think I'll have to leave this one out again as changing will require that I fully rebalance the weapon again which will take more than a few hours to do.

**Comment by Yeldur** [comment]
SCRAPPING THIS PR, REFER TO https://github.com/namidaka/itembalancing/pull/531

**Pull request closed without merging**
