### PR TITLE
Add Clan Color Brigandines trial 2

### PR DESCRIPTION
**Pull request by AppleTruce**
Added new clan color brigandines by apple, rebalanced old (color) brigandines with gambeson only underneath to fit with new brigs.  Filled area of old gambeson brigs with new mail underneath brigs.  This PR should replace PR497, 500 & 501 in a much  cleaner way.  All changes done in single PR.

### CODE REVIEW

**Review by AppleTruce — COMMENTED** [review]
Hey guys, this PR should replace all of my Brigandine PR's and was indeed made form those older PR's.  The only edit or change I made from the old PR's to this one, was to take Erdertus's feedback from PR501 about upreving the rev of the brigandines that would need to be refunded.  That is now completed as well.

**Review by AppleTruce — COMMENTED** [review]
> Hey guys, this PR should replace all of my Brigandine PR's and was indeed made form those older PR's.  The only edit or change I made from the old PR's to this one, was to take Erdertus's feedback from PR501 about upreving the rev of the brigandines that would need to be refunded.  That is now completed as well. 

Also, I will close and delete the old PR's once it looks like this one is correct.

**Review by Erdertus — CHANGES_REQUESTED** [review]
Screenshot_20241210-183438

This item + it's looms have AA in their name, can this be removed on the body_armors.xml and then rerun the Exporter to update the items.json, else in the shop they will have AA in the name :)

**Comment by AppleTruce** [comment]
You have an Eagle Eye @Erdertus thanks so much!  I removed that and re-ran exporter and recommitted.  CHecked and it's ghood now.  thanks.

**Review by Erdertus — APPROVED** [review]
Approved

**Review by Yeldur — APPROVED** [review]
Approved

**Review by Meowkov — APPROVED** [review]

**Pull request merged**
